# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from xycar_msgs/laneinfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class laneinfo(genpy.Message):
  _md5sum = "44a42243e734addbc7ddd0e00184e0ab"
  _type = "xycar_msgs/laneinfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 left_x
float32 left_y
float32 left_slope
float32 right_x
float32 right_y
float32 right_slope """
  __slots__ = ['left_x','left_y','left_slope','right_x','right_y','right_slope']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_x,left_y,left_slope,right_x,right_y,right_slope

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(laneinfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_x is None:
        self.left_x = 0.
      if self.left_y is None:
        self.left_y = 0.
      if self.left_slope is None:
        self.left_slope = 0.
      if self.right_x is None:
        self.right_x = 0.
      if self.right_y is None:
        self.right_y = 0.
      if self.right_slope is None:
        self.right_slope = 0.
    else:
      self.left_x = 0.
      self.left_y = 0.
      self.left_slope = 0.
      self.right_x = 0.
      self.right_y = 0.
      self.right_slope = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.left_x, _x.left_y, _x.left_slope, _x.right_x, _x.right_y, _x.right_slope))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.left_x, _x.left_y, _x.left_slope, _x.right_x, _x.right_y, _x.right_slope,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.left_x, _x.left_y, _x.left_slope, _x.right_x, _x.right_y, _x.right_slope))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.left_x, _x.left_y, _x.left_slope, _x.right_x, _x.right_y, _x.right_slope,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
